//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.5485
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HorizontalControllerEX_CT.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HorizontalControllerEX_CT.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Horizontal Controller EX Configuration Tool に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string APPLICATION_NAME {
            get {
                return ResourceManager.GetString("APPLICATION_NAME", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap BG_AB_active {
            get {
                object obj = ResourceManager.GetObject("BG_AB_active", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   clr に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CLEAR_BUTTON_TEXT {
            get {
                return ResourceManager.GetString("CLEAR_BUTTON_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Device Found に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DEVICE_FOUND {
            get {
                return ResourceManager.GetString("DEVICE_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Device not found に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DEVICE_NOT_FOUND {
            get {
                return ResourceManager.GetString("DEVICE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルのLOADに失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FILE_LOAD_ERR_MSG {
            get {
                return ResourceManager.GetString("FILE_LOAD_ERR_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   XML file(*.xml)|*.xml|All file(*.*)|*.* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FILE_OPEN_FILTER {
            get {
                return ResourceManager.GetString("FILE_OPEN_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FILE_OPEN_TITLE {
            get {
                return ResourceManager.GetString("FILE_OPEN_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルのSAVEに失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FILE_SAVE_ERR_MSG {
            get {
                return ResourceManager.GetString("FILE_SAVE_ERR_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   XML file(*.xml)|*.xml|All file(*.*)|*.* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FILE_SAVE_FILTER {
            get {
                return ResourceManager.GetString("FILE_SAVE_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save As... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FILE_SAVE_TITLE {
            get {
                return ResourceManager.GetString("FILE_SAVE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FW Version に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FW_VERSION {
            get {
                return ResourceManager.GetString("FW_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set Key に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KEYBOARD_INPUTKEY_TEXT {
            get {
                return ResourceManager.GetString("KEYBOARD_INPUTKEY_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input Key に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KEYBOARD_SET_KEY_EMPTY {
            get {
                return ResourceManager.GetString("KEYBOARD_SET_KEY_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   X, Y Vector に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MOUSE_MOVE_TEXT {
            get {
                return ResourceManager.GetString("MOUSE_MOVE_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scroll Val に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MOUSE_SCROLL_TEXT {
            get {
                return ResourceManager.GetString("MOUSE_SCROLL_TEXT", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap OFF {
            get {
                object obj = ResourceManager.GetObject("OFF", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OFF_Black {
            get {
                object obj = ResourceManager.GetObject("OFF_Black", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ON {
            get {
                object obj = ResourceManager.GetObject("ON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ON_Black {
            get {
                object obj = ResourceManager.GetObject("ON_Black", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   設定内容を初期化します。よろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RESET_WARNING_MSG {
            get {
                return ResourceManager.GetString("RESET_WARNING_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   一旦USBケーブルを抜いて、画面右下のデバイス検出済みからデバイス未検出になってから、USBケーブルを挿し直して下さい。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RESET_WARNING_MSG2 {
            get {
                return ResourceManager.GetString("RESET_WARNING_MSG2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   感度 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SENSIVITY_SET_TEXT {
            get {
                return ResourceManager.GetString("SENSIVITY_SET_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   KEYBOARD INPUT KEY に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SET_TYPE_KEYBOARD {
            get {
                return ResourceManager.GetString("SET_TYPE_KEYBOARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MOUSE DOUBLE CLICK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SET_TYPE_MOUSE_DOUBLE_CLICK {
            get {
                return ResourceManager.GetString("SET_TYPE_MOUSE_DOUBLE_CLICK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MOUSE L CLICK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SET_TYPE_MOUSE_L_CLICK {
            get {
                return ResourceManager.GetString("SET_TYPE_MOUSE_L_CLICK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MOUSE MOVE に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SET_TYPE_MOUSE_MOVE {
            get {
                return ResourceManager.GetString("SET_TYPE_MOUSE_MOVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MOUSE R CLICK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SET_TYPE_MOUSE_R_CLICK {
            get {
                return ResourceManager.GetString("SET_TYPE_MOUSE_R_CLICK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MOUSE WHEEL CLICK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SET_TYPE_MOUSE_WH_CLICK {
            get {
                return ResourceManager.GetString("SET_TYPE_MOUSE_WH_CLICK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MOUSE WHEEL SCROLL に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SET_TYPE_MOUSE_WH_SCROLL {
            get {
                return ResourceManager.GetString("SET_TYPE_MOUSE_WH_SCROLL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NONE に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SET_TYPE_NONE {
            get {
                return ResourceManager.GetString("SET_TYPE_NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   VOLUME DOWN に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SET_TYPE_VOLUME_DOWN {
            get {
                return ResourceManager.GetString("SET_TYPE_VOLUME_DOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   VOLUME MUTE に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SET_TYPE_VOLUME_MUTE {
            get {
                return ResourceManager.GetString("SET_TYPE_VOLUME_MUTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   VOLUME UP に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SET_TYPE_VOLUME_UP {
            get {
                return ResourceManager.GetString("SET_TYPE_VOLUME_UP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定完了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SET_WRITE_COMP_MSG {
            get {
                return ResourceManager.GetString("SET_WRITE_COMP_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファームウェアの書き換えを開始します。よろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SOFT_RESET_WARNING_MSG {
            get {
                return ResourceManager.GetString("SOFT_RESET_WARNING_MSG", resourceCulture);
            }
        }
    }
}
